import type { NextPage } from "next";
import Head from "next/head";
import NavBar from "../components/navbar";
import WordInput from "../components/wordInput";
import Heading from "../components/heading";
import Progress from "../components/progress";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>DickTion</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <NavBar></NavBar>
      <Heading sentence={"영어 발음 검색기"}></Heading>
      <WordInput></WordInput>
      <Progress now={66}></Progress>
    </>
  );
};

export default Home;
